name: Release
on:
  workflow_run:
    workflows: 
    - Run Test
    types: 
    - completed
    branches:
    - release**
    - hotfix**
    - feature**
  push:
    tags:
    - v*.*.*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  docker:
    name: Build And Publish Docker Image
    if: ${{ github.event.workflow_run.conclusion == 'success' }} || startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref, event=tag
          type=ref, event=branch
          type=ref, event=pr
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        token:  ${{ secrets.PAT }}
