name: Release Build
on:
  workflow_run:
    workflows: ["Run Test"]
    types: 
    - completed
    branches:
    - master

jobs:
  docker:
    name: Build And Publish Docker Image
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Auto Tag
      run: |
        git config --global user.name "Github Action Bot"
        git config --global user.email "jacexh@users.noreply.github.com"
        type=patch
        pattern="^Merge pull request #[0-9]+ from jacexh/release.*"
        echo "commit message: $COMMIT_MESSAGE"
        if [[ $COMMIT_MESSAGE =~ $pattern ]]; then
          echo "bump up minor version number"
          type=minor
        fi
        ./scripts/auto_bump_version.sh $type
        echo "NEXT_VERSION=`cat next_version.txt` >> $GITHUB_ENV
        git push origin master --follow-tags
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=raw,value=${{ env.NEXT_VERSION }}
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
