name: Run Test

on:
  push:
    branches:
    - release**
    - hotfix**
    - feature**
    - master
  pull_request:
    types:
    - opened
    - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  unittest:
    name: Run Unit TestCases
    strategy:
      fail-fast: true
      matrix:
        go-version: [1.24.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Check out code into the Go module directory
    - uses: actions/setup-go@v5
      name: Set up Go 1.x
      with:
        go-version: ${{matrix.go-version}}
    - name: Run TestCases
      run: make unittest
    - name: Save code coverage results
      if: ${{matrix.go-version == '1.24.x' }}
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage.txt
    - name: Run Benchmark TestCases
      run: make benchmark

  codecov:
    name: Upload Code Coverage Report
    runs-on: ubuntu-latest
    needs: unittest
    steps:
    - uses: actions/checkout@v4
    - name: Download code coverage report
      uses: actions/download-artifact@v4
      with:
        name: code-coverage-report
    - uses: codecov/codecov-action@v5
      with:
        files: coverage.txt # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
        token: ${{ secrets.CODECOV_TOKEN }}