name: Docker Build
on:
  workflow_run:
    workflows: ["Run Test"]
    types: 
    - completed
  workflow_dispatch:
  push:
    branches:
    - release**
    - hotfix**
    - feature**

jobs:
  docker:
    name: Build And Publish Docker Image
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref, event=tag
          type=ref, event=branch
          type=ref, event=pr
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
